Add jetty collection to gz-collections.yaml
gazebo-tooling/release-tools pull request #1199
Opened 2024-11-06 14:02 UTC by Crola1702

As the title says

2024-11-06 16:19 UTC, j-rivero commented
If I'm not wrong the appointed branches for Jetty are already setup in https://github.com/gazebo-tooling/gazebodistro/pull/181 and should be the same here. So no `main` branches but probably starting with Ionic branches.

2024-11-06 21:09 UTC, Crola1702 commented
> So no main branches but probably starting with Ionic branches.

Done. Can you check if everything is correct? @j-rivero

2024-11-08 19:37 UTC, j-rivero requested changes
I think that major_version are not in sync with the package names. I.e: gz-cmake4 branch for gz-cmake5 package. So we need to update the major_versions too.

2024-11-11 16:48 UTC, azeey commented on jenkins-scripts/dsl/gz-collections.yaml
> +          current_branch: gz-cmake5
We should do the opposite here. Currently, Jetty should be the exact copy of Ionic.

2024-11-12 20:28 UTC, j-rivero approved these changes

2024-11-12 20:47 UTC, merged